[package]
name = "simple-icons-website-controls-layout-types"
description = "Types and signals for layout control for the Simple Icons website"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
leptos.workspace = true
