[package]
name = "simple-icons-website-storage"
description = "Local storage for the Simple Icons website"
version.workspace = true
edition.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
web-sys.workspace = true
